config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts
  resources :user_achievements
  resources :products
  resources :achievements
  resources :purchases
  resources :coupons
  resources :combos
  resources :waiting_lists
  resources :payment_methods
  resources :events
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root :to => "events#index"

  # Sidekiq web config
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
  end

  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combo.rb
class Combo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates_presence_of :payment_method
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
end

app/models/waiting_list.rb
class WaitingList < ApplicationRecord
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :set_combo, only: [:show, :edit, :update, :destroy]

  # GET /combos
  # GET /combos.json
  def index
    @combos = Combo.all
  end

  # GET /combos/1
  # GET /combos/1.json
  def show
  end

  # GET /combos/new
  def new
    @combo = Combo.new
  end

  # GET /combos/1/edit
  def edit
  end

  # POST /combos
  # POST /combos.json
  def create
    @combo = Combo.new(combo_params)

    respond_to do |format|
      if @combo.save
        format.html { redirect_to @combo, notice: 'Combo was successfully created.' }
        format.json { render :show, status: :created, location: @combo }
      else
        format.html { render :new }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combos/1
  # PATCH/PUT /combos/1.json
  def update
    respond_to do |format|
      if @combo.update(combo_params)
        format.html { redirect_to @combo, notice: 'Combo was successfully updated.' }
        format.json { render :show, status: :ok, location: @combo }
      else
        format.html { render :edit }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combos/1
  # DELETE /combos/1.json
  def destroy
    @combo.destroy
    respond_to do |format|
      format.html { redirect_to combos_url, notice: 'Combo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combo
      @combo = Combo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combo_params
      params.require(:combo).permit(:event_id, :product_id, :name, :price, :qty)
    end
end

app/controllers/waiting_lists_controller.rb
class WaitingListsController < ApplicationController
  before_action :set_waiting_list, only: [:show, :edit, :update, :destroy]

  # GET /waiting_lists
  # GET /waiting_lists.json
  def index
    @waiting_lists = WaitingList.all
  end

  # GET /waiting_lists/1
  # GET /waiting_lists/1.json
  def show
  end

  # GET /waiting_lists/new
  def new
    @waiting_list = WaitingList.new
  end

  # GET /waiting_lists/1/edit
  def edit
  end

  # POST /waiting_lists
  # POST /waiting_lists.json
  def create
    @waiting_list = WaitingList.new(waiting_list_params)

    respond_to do |format|
      if @waiting_list.save
        format.html { redirect_to @waiting_list, notice: 'Waiting list was successfully created.' }
        format.json { render :show, status: :created, location: @waiting_list }
      else
        format.html { render :new }
        format.json { render json: @waiting_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waiting_lists/1
  # PATCH/PUT /waiting_lists/1.json
  def update
    respond_to do |format|
      if @waiting_list.update(waiting_list_params)
        format.html { redirect_to @waiting_list, notice: 'Waiting list was successfully updated.' }
        format.json { render :show, status: :ok, location: @waiting_list }
      else
        format.html { render :edit }
        format.json { render json: @waiting_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waiting_lists/1
  # DELETE /waiting_lists/1.json
  def destroy
    @waiting_list.destroy
    respond_to do |format|
      format.html { redirect_to waiting_lists_url, notice: 'Waiting list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waiting_list
      @waiting_list = WaitingList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def waiting_list_params
      params.require(:waiting_list).permit(:user_id, :event_id, :entry_date)
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_events
    array = []
    events = Event.where(owner: current_user.name)

    events.each do |event|
      array << [event.name, event.id]
    end

    array
  end
end

app/helpers/combos_helper.rb
module CombosHelper

  def my_products
    array = []
    events = Event.where(owner: current_user.name).to_a

    products = Product.where(event_id: events)

    products.each do |product|
      array << [product.name, product.id]
    end

    array
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def events_categories
    [
      ['Games', 'games'],
      ['Festa', 'festa'],
      ['Programação', 'progamacao'],
      ['Música', 'musica'],
      ['Cinema', 'cinema'],
      ['Palestra', 'palestra'],
      ['Outros', 'outros']
    ]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def payment_methods
    PaymentMethod.where(user_id: current_user.id).pluck(:nickname)
  end
end

app/helpers/waiting_lists_helper.rb
module WaitingListsHelper
end

app/views/waiting_lists/_form.html.erb
<%= form_with(model: waiting_list, local: true) do |form| %>
  <% if waiting_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waiting_list.errors.count, "error") %> prohibited this waiting_list from being saved:</h2>

      <ul>
      <% waiting_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :user_id, :style=>'display:block;' %>
    <%= form.number_field :user_id, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :event_id, :style=>'display:block;' %>
    <%= form.number_field :event_id, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :entry_date, :style=>'display:block;' %>
    <%= form.datetime_select :entry_date, :style=>'display:block; width:100%' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waiting_lists/edit.html.erb
<h1>Editing Waiting List</h1>

<div class="container">
  <%= render 'form', waiting_list: @waiting_list %>
</div>

<div class="container" style="text-align:center">
  <button><%= link_to '<-Back', waiting_lists_path %></button>
  <button><%= link_to 'Show', @waiting_list %></button>
</div>

app/views/waiting_lists/index.html.erb
<h1 style="text-align:center">Waiting Lists</h1>

<p id="notice"><%= notice %></p>

<table class="table table-striped" style="border: 1px solid #fff; border-radius: 24px;">
  <thead style="background:#000; color:#fff">
    <tr>
      <th>User</th>
      <th>Evento</th>
      <th>Data Req</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @waiting_lists.each do |waiting_list| %>
      <tr>
        <td><%= waiting_list.user_id %></td>
        <td><%= waiting_list.event_id %></td>
        <td><%= waiting_list.entry_date %></td>
        <td><%= link_to 'Show', waiting_list %></td>
        <td><%= link_to 'Edit', edit_waiting_list_path(waiting_list) %></td>
        <td><%= link_to 'Destroy', waiting_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to 'New Waiting List', new_waiting_list_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/waiting_lists/new.html.erb
<h1 style="text-align:center">New Waiting List</h1>

<div class="container">
  <%= render 'form', waiting_list: @waiting_list %>
</div>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to '<-Back', waiting_lists_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/waiting_lists/show.html.erb
<h1 style="text-align:center">Detalhes Espera</h1>

<p id="notice"><%= notice %></p>

<div class="container" style="text-align:center; height:100%">
  <p>
    <strong>User:</strong>
    <%= @waiting_list.user_id %>
  </p>

  <p>
    <strong>Event:</strong>
    <%= @waiting_list.event_id %>
  </p>

  <p>
    <strong>Entry date:</strong>
    <%= @waiting_list.entry_date %>
  </p>
  
  <button><%= link_to '<-Back', waiting_lists_path %></button>
  <button><%= link_to 'Edit', edit_waiting_list_path(@waiting_list) %></button>

</div>