config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts
  resources :user_achievements
  resources :products
  resources :achievements
  resources :purchases
  resources :coupons
  resources :combos
  resources :waiting_lists
  resources :payment_methods
  resources :events
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root :to => "events#index"

  # Sidekiq web config
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
  end

  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combo.rb
class Combo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates_presence_of :payment_method
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
end

app/models/waiting_list.rb
class WaitingList < ApplicationRecord
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.where(user_id: current_user.id).to_a
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    params[:payment_method][:user_id] = current_user.id
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:user_id, :nickname, :card_holder, :card_number, :card_expiration_month, :card_expiration_year)
    end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_events
    array = []
    events = Event.where(owner: current_user.name)

    events.each do |event|
      array << [event.name, event.id]
    end

    array
  end
end

app/helpers/combos_helper.rb
module CombosHelper

  def my_products
    array = []
    events = Event.where(owner: current_user.name).to_a

    products = Product.where(event_id: events)

    products.each do |product|
      array << [product.name, product.id]
    end

    array
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def events_categories
    [
      ['Games', 'games'],
      ['Festa', 'festa'],
      ['Programação', 'progamacao'],
      ['Música', 'musica'],
      ['Cinema', 'cinema'],
      ['Palestra', 'palestra'],
      ['Outros', 'outros']
    ]
  end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def payment_methods
    PaymentMethod.where(user_id: current_user.id).pluck(:nickname)
  end
end

app/helpers/waiting_lists_helper.rb
module WaitingListsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_with(model: payment_method, local: true) do |form| %>
  <% if payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :nickname, :style=>'display:block;' %>
    <%= form.text_field :nickname, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :card_holder, :style=>'display:block;' %>
    <%= form.text_field :card_holder, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :card_number, :style=>'display:block;' %>
    <%= form.number_field :card_number, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :card_expiration_month, :style=>'display:block;' %>
    <%= form.number_field :card_expiration_month, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :card_expiration_year, :style=>'display:block;' %>
    <%= form.number_field :card_expiration_year, :style=>'display:block; width:100%' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<div class="container">
  <%= render 'form', payment_method: @payment_method %>
</div>

<div class="container" style="text-align:center">
  <button><%= link_to '<-Back', payment_methods_path %></button>
  <button><%= link_to 'Show', @payment_method %></button>
</div>

app/views/payment_methods/index.html.erb
<h1 style="text-align:center">Payment Methods</h1>

<p id="notice"><%= notice %></p>

<table class="table table-striped" style="border: 1px solid #fff; border-radius: 24px;">
  <thead style="background:#000; color:#fff">
    <tr>
      <th>Apelido</th>
      <th>Card Holder</th>
      <th>Card Number</th>
      <th>Card Expiration</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_methods.each do |payment_method| %>
      <tr>
        <td><%= payment_method.nickname %></td>
        <td><%= payment_method.card_holder %></td>
        <td><%= payment_method.card_number %></td>
        <td><%= "#{payment_method.card_expiration_month}/#{payment_method.card_expiration_year}" %></td>
        <td><%= link_to 'Show', payment_method %></td>
        <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
        <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to 'New Payment Method', new_payment_method_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/payment_methods/new.html.erb
<h1 style="text-align:center">New Payment Method</h1>

<div class="container">
  <%= render 'form', payment_method: @payment_method %>
</div>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to '<-Back', payment_methods_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/payment_methods/show.html.erb
<h1 style="text-align:center">Detalhes Pagamento</h1>

<p id="notice"><%= notice %></p>

<div class="container" style="text-align:center; height:100%">
  <p>
    <strong>Nickname:</strong>
    <%= @payment_method.nickname %>
  </p>

  <p>
    <strong>Card holder:</strong>
    <%= @payment_method.card_holder %>
  </p>

  <p>
    <strong>Card number:</strong>
    <%= @payment_method.card_number %>
  </p>

  <p>
    <strong>Card Expiration:</strong>
    <%= "#{@payment_method.card_expiration_month}/#{@payment_method.card_expiration_year}" %>
  </p>
  
  <button><%= link_to '<-Back', payment_methods_path %></button>
  <button><%= link_to 'Edit', edit_payment_method_path(@payment_method) %></button>

</div>