config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts
  resources :user_achievements
  resources :products
  resources :achievements
  resources :purchases
  resources :coupons
  resources :combos
  resources :waiting_lists
  resources :payment_methods
  resources :events
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root :to => "events#index"

  # Sidekiq web config
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
  end

  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combo.rb
class Combo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates_presence_of :payment_method
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
end

app/models/waiting_list.rb
class WaitingList < ApplicationRecord
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_events
    array = []
    events = Event.where(owner: current_user.name)

    events.each do |event|
      array << [event.name, event.id]
    end

    array
  end
end

app/helpers/combos_helper.rb
module CombosHelper

  def my_products
    array = []
    events = Event.where(owner: current_user.name).to_a

    products = Product.where(event_id: events)

    products.each do |product|
      array << [product.name, product.id]
    end

    array
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def events_categories
    [
      ['Games', 'games'],
      ['Festa', 'festa'],
      ['Programação', 'progamacao'],
      ['Música', 'musica'],
      ['Cinema', 'cinema'],
      ['Palestra', 'palestra'],
      ['Outros', 'outros']
    ]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def payment_methods
    PaymentMethod.where(user_id: current_user.id).pluck(:nickname)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Uningressos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="paige-container">
    <%= render "shared/header" %>
    <% if user_signed_in? %>
      <%= render "shared/navbar" %>
    <% end %>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      <footer class="footer">
        Logado como: <strong><%= current_user.email %></strong>.
        <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %>
      </footer>
    <% else %>
      <footer class="footer">
        <span>Uningressos - Xuaum e Camileski</span>
      </footer>
    <% end %>
    <div>
  </body>
</html>

app/views/shared/_header.html.erb
<div class="gradient-header" style="height:25vh">
  <h1 class="vectro"><span class="vectro-body">UNINGRESSOS</span><span class="vectro-red">I</span><span class="vectro-green">I</span><span class="vectro-blue">I</span></h1>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark" style="margin:0;">

  <!-- Links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= link_to 'Eventos', events_path(@events), {:class=>'nav-link'} %>
    </li>

    <li class="nav-item">
      <%= link_to 'Combos', combos_path(@combos), {:class=>'nav-link'} %>
    </li>

    <li class="nav-item">
      <%= link_to 'Produtos', products_path(@products), {:class=>'nav-link'} %>
    </li>

    <% if current_user.admin? %>
      <li class="nav-item">
        <%= link_to 'Cupons', coupons_path(@coupons), {:class=>'nav-link'} %>
      </li>
    <% end %>

  <% if !current_user.admin? %>
    <li class="nav-item">
      <%= link_to 'Pagamento', payment_methods_path(@payment_methods), {:class=>'nav-link'} %>
    </li>

    <li class="nav-item">
        <%= link_to 'Compras', purchases_path(@purchases), {:class=>'nav-link'} %>
    </li>

    <li class="nav-item">
        <%= link_to 'Contatos', contacts_path(@contacts), {:class=>'nav-link'} %>
    </li>

  <% end %>
  </ul>
</nav>