config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts
  resources :user_achievements
  resources :products
  resources :achievements
  resources :purchases
  resources :coupons
  resources :combos
  resources :waiting_lists
  resources :payment_methods
  resources :events
  devise_for :users, controllers: { sessions: "users/sessions", registrations: "users/registrations" }

  root :to => "events#index"

  # Sidekiq web config
  mount Sidekiq::Web => '/sidekiq'

  Sidekiq::Web.use(Rack::Auth::Basic) do |user, password|
    [user, password] == [ENV["SIDEKIQ_USERNAME"], ENV["SIDEKIQ_PASSWORD"]]
  end

  Sidekiq::Web.set :session_secret, Rails.application.secrets[:secret_key_base]
end

app/models/achievement.rb
class Achievement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/combo.rb
class Combo < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/coupon.rb
class Coupon < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  validates_presence_of :payment_method
end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_achievement.rb
class UserAchievement < ApplicationRecord
end

app/models/waiting_list.rb
class WaitingList < ApplicationRecord
end

app/controllers/combos_controller.rb
class CombosController < ApplicationController
  before_action :set_combo, only: [:show, :edit, :update, :destroy]

  # GET /combos
  # GET /combos.json
  def index
    @combos = Combo.all
  end

  # GET /combos/1
  # GET /combos/1.json
  def show
  end

  # GET /combos/new
  def new
    @combo = Combo.new
  end

  # GET /combos/1/edit
  def edit
  end

  # POST /combos
  # POST /combos.json
  def create
    @combo = Combo.new(combo_params)

    respond_to do |format|
      if @combo.save
        format.html { redirect_to @combo, notice: 'Combo was successfully created.' }
        format.json { render :show, status: :created, location: @combo }
      else
        format.html { render :new }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /combos/1
  # PATCH/PUT /combos/1.json
  def update
    respond_to do |format|
      if @combo.update(combo_params)
        format.html { redirect_to @combo, notice: 'Combo was successfully updated.' }
        format.json { render :show, status: :ok, location: @combo }
      else
        format.html { render :edit }
        format.json { render json: @combo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /combos/1
  # DELETE /combos/1.json
  def destroy
    @combo.destroy
    respond_to do |format|
      format.html { redirect_to combos_url, notice: 'Combo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_combo
      @combo = Combo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def combo_params
      params.require(:combo).permit(:event_id, :product_id, :name, :price, :qty)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    if current_user.admin?
      if params[:name] || params[:description] || params[:owner]
        @events = Event.where(
          'name LIKE :name AND description LIKE :description AND owner LIKE :owner AND category LIKE :category',
          name: "%#{params[:name]}%",
          description: "%#{params[:description]}%",
          owner: "%#{current_user.name}%",
          category: "%#{params[:category]}%"
        )
      else
        @events = Event.where(owner: current_user.name)
      end
    else
      if params[:name] || params[:description] || params[:owner]
        @events = Event.where(
          'name LIKE :name AND description LIKE :description AND owner LIKE :owner AND category LIKE :category',
          name: "%#{params[:name]}%",
          description: "%#{params[:description]}%",
          owner: "%#{params[:owner]}%",
          category: "%#{params[:category]}%"
        )
      else
        @events = Event.all
      end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @owner = User.where(name: @event.owner).first
    @products = Product.where(event_id: @event.id).to_a
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    params[:event][:owner] = current_user.name
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Never truANDANDst parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :qty, :description, :date, :price, :owner, :category)
  end
end

app/helpers/achievements_helper.rb
module AchievementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def my_events
    array = []
    events = Event.where(owner: current_user.name)

    events.each do |event|
      array << [event.name, event.id]
    end

    array
  end
end

app/helpers/combos_helper.rb
module CombosHelper

  def my_products
    array = []
    events = Event.where(owner: current_user.name).to_a

    products = Product.where(event_id: events)

    products.each do |product|
      array << [product.name, product.id]
    end

    array
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/events_helper.rb
module EventsHelper

  def events_categories
    [
      ['Games', 'games'],
      ['Festa', 'festa'],
      ['Programação', 'progamacao'],
      ['Música', 'musica'],
      ['Cinema', 'cinema'],
      ['Palestra', 'palestra'],
      ['Outros', 'outros']
    ]
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper

  def payment_methods
    PaymentMethod.where(user_id: current_user.id).pluck(:nickname)
  end
end

app/helpers/waiting_lists_helper.rb
module WaitingListsHelper
end

app/views/combos/_form.html.erb
<%= form_with(model: combo, local: true) do |form| %>
  <% if combo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(combo.errors.count, "error") %> prohibited this combo from being saved:</h2>

      <ul>
      <% combo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :event_id, :style=>'display:block;' %>
    <%= form.select :event_id, my_events, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :product_id, :style=>'display:block;' %>
    <%= form.select :product_id, my_products, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :name, :style=>'display:block;' %>
    <%= form.text_field :name, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :price, :style=>'display:block;' %>
    <%= form.text_field :price, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :qty, :style=>'display:block;' %>
    <%= form.number_field :qty, :style=>'display:block; width:100%' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/combos/edit.html.erb
<h1 style="text-align:center">Editar Combo</h1>

<div class="container">
  <%= render 'form', combo: @combo %>
</div>

<div class="container" style="text-align:center">
  <button><%= link_to '<-Back', combos_path %></button>
  <button><%= link_to 'Show', @combo %></button>
</div>

app/views/combos/index.html.erb
<h1 style="text-align:center">Combos</h1>

<p id="notice"><%= notice %></p>

<table class="table table-striped" style="border: 1px solid #fff; border-radius: 24px;">
  <thead style="background:#000; color:#fff">
    <tr>
      <th>Evento</th>
      <th>Produto</th>
      <th>Nome</th>
      <th>Preço</th>
      <th>Qtde</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @combos.each do |combo| %>
      <tr>
        <td><%= Event.find(combo.event_id).name %></td>
        <td><%= Product.find(combo.product_id).name %></td>
        <td><%= combo.name %></td>
        <td><%= combo.price %></td>
        <td><%= combo.qty %></td>
        <td><%= link_to 'Show', combo %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_combo_path(combo) %></td>
          <td><%= link_to 'Destroy', combo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.admin? %>
  <div class="container" style="text-align:center">
      <button type="button" class="btn btn-primary btn-lg"><%= link_to 'New Combo', new_combo_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
  </div>
<% end %>

app/views/combos/new.html.erb
<h1 style="text-align:center">Novo Combo</h1>

<div class="container">
  <%= render 'form', combo: @combo %>
</div>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to 'Back', combos_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/combos/show.html.erb
<h1 style="text-align:center">Detalhes Combo</h1>

<p id="notice"><%= notice %></p>

<div class="container" style="text-align:center; height:100%">
  <p>
    <strong>Event:</strong>
    <%= Event.find(@combo.event_id).name %>
  </p>

  <p>
    <strong>Product:</strong>
    <%= Product.find(@combo.product_id).name %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= @combo.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @combo.price %>
  </p>

  <p>
    <strong>Qty:</strong>
    <%= @combo.qty %>
  </p>

  <% if !current_user.admin? %>
    <p>
      <%= link_to 'Comprar Combo', { "controller" => "purchases", "action"=>"new", :item_id => @combo.id, :type => 'combo' } %>
    </p>
  <% end %>

  <button><%= link_to '<-Back', combos_path %></button>
  <% if current_user.admin? %>
    <button><%= link_to 'Edit', edit_combo_path(@combo) %></button>
  <% end %>

</div>

app/views/events/_filter.html.erb
<%= form_for "", url: events_path, method: :get, html: {id: 'course_filter'}, wrapper: 'input_mdb' do |form| %>
<h2>Filtrar Eventos</h2>
  <div class="field" style="padding-bottom:2vh">
    <%= form.label :name, :style=>'display:block' %>
    <%= form.text_field :name, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :description, :style=>'display:block' %>
    <%= form.text_field :description, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :owner, :style=>'display:block' %>
    <%= form.text_field :owner, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :category, :style=>'display:block' %>
    <%= form.text_field :category, :style=>'display:block; width:100%' %>
  </div>

  <div class="actions" style="text-align:center">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :name, :style=>'display:block;' %>
    <%= form.text_field :name, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :qty, :style=>'display:block;' %>
    <%= form.number_field :qty, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :description, :style=>'display:block;' %>
    <%= form.text_field :description, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :date, :style=>'display:block;' %>
    <%= form.datetime_select :date, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :price, :style=>'display:block;' %>
    <%= form.text_field :price, :style=>'display:block; width:100%' %>
  </div>

  <div class="field" style="padding-bottom:2vh">
    <%= form.label :category, :style=>'display:block;' %>
    <%= form.select :category, events_categories, :style=>'display:block; width:100%' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 style="text-align:center">Editar Evento</h1>

<div class="container">
  <%= render 'form', event: @event %>
</div>

<div class="container" style="text-align:center">
  <button><%= link_to '<-Back', events_path %></button>
  <button><%= link_to 'Show', @event %></button>
</div>

app/views/events/index.html.erb
<h1 style="text-align:center">Eventos</h1>

<div class="container">
  <%= render partial: 'filter' %>
</div>

<p id="notice"><%= notice %></p>

<table class="table table-striped" style="border: 1px solid #fff; border-radius: 24px;">
  <thead style="background:#000; color:#fff">
    <tr>
      <th>Nome</th>
      <th>Vagas</th>
      <th>Descrição</th>
      <th>Data</th>
      <th>Preço</th>
      <th>Categoria</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody >
    <% @events.each do |event| %>
      <tr style="background:#d3d3d3; color:#000">
        <td><%= event.name %></td>
        <td><%= event.qty %></td>
        <td><%= event.description %></td>
        <td><%= event.date %></td>
        <td><%= event.price %></td>
        <td><%= event.category %></td>
        <td><%= link_to 'Show', event %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<% if current_user.admin? %>
  <div class="container" style="text-align:center">
      <button type="button" class="btn btn-primary btn-lg"><%= link_to 'Novo Evento', new_event_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
  </div>
<% end %>

app/views/events/new.html.erb
<h1 style="text-align:center">Novo Evento</h1>

<div class="container">
  <%= render 'form', event: @event %>
</div>

<div class="container" style="text-align:center">
    <button type="button" class="btn btn-primary btn-lg"><%= link_to '<-Back', events_path, {:class=>'nav-item', :style=>'color:#fff'} %></button>
</div>

app/views/events/show.html.erb
<h1 style="text-align:center">Detalhes Evento</h1>

<p id="notice"><%= notice %></p>

<div class="container" style="text-align:center; height:100%">
  <p>
    <strong>Name:</strong>
    <%= @event.name %>
  </p>

  <p>
    <strong>Vacancy:</strong>
    <%= @event.qty %>
  </p>

  <p>
    <strong>Desc:</strong>
    <%= @event.description %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= @event.date %>
  </p>

  <p>
    <strong>price:</strong>
    <%= @event.price %>
  </p>

  <p>
    <strong>price:</strong>
    <%= @event.category %>
  </p>

  <% if !current_user.admin? %>
    <p>
      <%= link_to 'Enviar mensagem para o organizador', { "controller" => "contacts", "action"=>"new", :event => @event.id, :receiver => @owner.id, :broadcast => false } %>
    </p>

    <p>
      <%= link_to 'Comprar Ingresso', { "controller" => "purchases", "action"=>"new", :item_id => @event.id, :type => 'event' } %>
    </p>
  <% else %>
    <p>
      <%= link_to 'Enviar mensagem para todos participantes', { "controller" => "contacts", "action"=>"new", :event => @event.id, :receiver => @owner.id, :broadcast => true } %>
    </p>

    <p>
      <%= link_to 'Cadastrar produto relacionado', { "controller" => "products", "action"=>"new", :event => @event.id } %>
    </p>
  <% end %>

<% if  !@products.blank? %>
  <h2> Produtos relacionados </h2>

  <% @products.each do |product| %>
    <div>
      <strong> <%= product.name %> </strong>
      <p> <%= product.description %> </p>
      <p> <%= product.price %> </p>
      <p> <%= product.qty %> </p>
      <td><%= link_to 'Show', product %></td>
    </div>
  <% end %>
<% end %>

<br><br>
<h2> Compartilhe nas redes sociais </h2>
<%= social_share_button_tag(@event.name) %>

  <button><%= link_to '<-Back', events_path %></button>
  <% if !current_user.admin? %>
    <button><%= link_to 'Edit', edit_event_path(@event) %></button>
  <% end %>
</div>